### PR TITLE
Added an A06 line

### PR DESCRIPTION
**Pull request by EthanHiser**

### CODE REVIEW

**Comment by niklasf** [comment]
Hi @EthanHiser. The columms are supposed to be separated by tabs. If you make additional edits on your branch, the pull request will be updated automatically - no need to create a new pull request for each attempt.

**Comment by EthanHiser** [comment]
Thanks for the help, @niklasf. This is the first time I've ever contributed to code that isn't mine. Now that the checks have passed is this pull request ok?

**Comment by cmgchess** [comment]
btw do you have some source for this? I couldn't find it on google

**Comment by EthanHiser** [comment]
Yeah, I found this variation in a chess book - Tennison Gambit by John Lutes

**Comment by niklasf** [comment]
Thanks!

**Pull request merged**
